name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : erdong
      USER_EMAIL  : erdong@mail.erdong.site
      BOOK_DIR    : /root

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Build and Deploy 🚀
      uses: onejar99/gitbook-build-publish-action@v1.0.3

