name: Build Gitbook Pages

# 触发条件，在 Push 到 Master 分支后触发。

on:
  push:
    branches:
      - master

# 任务

jobs:

  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
# 安装依赖
      - name: Install Dependencies version
        run: npm --version
      - name: 2. setup nodejs...
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm install gitbook-cli -g
#
## 检出代#码
#      - name: Checkout
#        uses: actions/chectout@master
#          
## 清空目#录
#      - name: Clean temp directory
#        run: rm -rf *
#        working-directory: ./docs
